### ISSUE TITLE
problems testing lsignal

### ISSUE THREAD

**Issue by alexwennstrom** [cpp11nullptr/lsignal#1]
Some found issues during testing:

1. Calling a signal with no connections does not work.

2. Setting one owner to several signals does not work. Only one signal (the last one) gets notified about owner getting destructed the other signals crashes when trying to call functions in destructed object.

3. When connecting signal1 to signal2, if signal2 gets destructed signal1 is informed but if signal1 gets destructed first, signal2 crashes in destructor when trying to remove itself from already destructed signal1.

alex.wennstrom@gmail.com.

**Comment by cpp11nullptr** [comment]
Thank you for your feedback, the issue has been fixed.
